#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d 6 7 8 9 10
bspc monitor DP-2 -s HDMI-1

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# start resources
xrdb merge ~/.Xresources

$HOME/.config/polybar/launch.sh &
pgrep -x redshift > /dev/null || redshift &

picom --config $HOME/.config/picom/1.conf &

flameshot &
