;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/top]
monitor = DP-2
width =  100%
height = 26
padding-left = 1
padding-right = 1
module-margin = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-size = 7
border-color = ${colors.background}
fixed-center = true
line-size = 3


modules-left = round-left bspwm round-right
modules-center = temperature space space memory space space cpu
modules-right = xbacklight alsa xkeyboard round-left time round-right space powermenu

font-0 = FiraCode Nerd Font:style=Bold:pixelsize=13;3
font-1 = JetBrainsMono Nerd Font:size=18;5
font-2 = Material Design Icons:style=Bold:size=13;3
font-3 = unifont:fontformat=truetype:size=13:antialias=true;


[bar/top2]
monitor = HDMI-1
width =  100%
height = 26
padding-left = 1
padding-right = 1
module-margin = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-size = 7
border-color = ${colors.background}
fixed-center = true
line-size = 3


modules-left = round-left bspwm round-right
modules-center = temperature space space memory space space cpu
modules-right = xbacklight alsa xkeyboard round-left time round-right space powermenu

font-0 = FiraCode Nerd Font:style=Bold:pixelsize=13;3
font-1 = JetBrainsMono Nerd Font:size=18;5
font-2 = Material Design Icons:style=Bold:size=13;3
font-3 = unifont:fontformat=truetype:size=13:antialias=true;

